<?xml version="1.0" encoding="UTF-8"?>
<!-- editado con XMLSpy v2019 sp1 (x64) (http://www.altova.com) por AEAT (Agencia Estatal de Administracion Tributaria ((AEAT))) -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" 

xmlns:sfLR="https://www.agenciatributaria.es/static_files/AEAT_Desarrolladores/EEDD/IVA/VERI-FACTU/Esquemas-SWeb/SuministroLR.xsd" xmlns:sf="https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/SuministroInformacion.xsd" 
xmlns:sfR="https://www.agenciatributaria.es/static_files/AEAT_Desarrolladores/EEDD/IVA/VERI-FACTU/Esquemas-SWeb/RespuestaSuministro.xsd"  xmlns:sfWdsl="https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/SistemaFacturacion.wsdl" xmlns:ns="http://www.w3.org/2000/09/xmldsig#" targetNamespace="https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/SistemaFacturacion.wsdl">
	<wsdl:types>
		<xs:schema targetNamespace="https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/SistemaFacturacion.wsdl" 
		     elementFormDefault="qualified" 
			 xmlns:sfWdsl="https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/SistemaFacturacion.wsdl" 
			 xmlns:sf="https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/tike/cont/ws/SuministroInformacion.xsd" 
			 xmlns:sfLR="https://www.agenciatributaria.es/static_files/AEAT_Desarrolladores/EEDD/IVA/VERI-FACTU/Esquemas-SWeb/SuministroLR.xsd">
			<xs:import namespace="https://www.agenciatributaria.es/static_files/AEAT_Desarrolladores/EEDD/IVA/VERI-FACTU/Esquemas-SWeb/SuministroInformacion.xsd" 
			schemaLocation="SuministroInformacion.xsd"/>
			<xs:import namespace="https://www.agenciatributaria.es/static_files/AEAT_Desarrolladores/EEDD/IVA/VERI-FACTU/Esquemas-SWeb/SuministroLR.xsd" 
			schemaLocation="SuministroLR.xsd"/>
			
			<xs:import namespace="https://www.agenciatributaria.es/static_files/AEAT_Desarrolladores/EEDD/IVA/VERI-FACTU/Esquemas-SWeb/RespuestaSuministro.xsd" schemaLocation="RespuestaSuministro.xsd"/>		</xs:schema>
	</wsdl:types>
	<wsdl:message name="EntradaRegFactuSistemaFacturacion">
		<wsdl:part name="RegFactuSistemaFacturacion" element="sfLR:RegFactuSistemaFacturacion"/>
	</wsdl:message>
	
	<wsdl:message name="RespuestaRegFactuSistemaFacturacion">
		<wsdl:part name="RespuestaRegFactuSistemaFacturacion" element="sfR:RespuestaRegFactuSistemaFacturacion"/>
	</wsdl:message>
	
	<wsdl:portType name="sfSOAP1">
		<wsdl:operation name="RegFactuSistemaFacturacion">
			<wsdl:input message="sfWdsl:EntradaRegFactuSistemaFacturacion"/>
			<wsdl:output message="sfWdsl:RespuestaRegFactuSistemaFacturacion"/>
		</wsdl:operation>
	
	</wsdl:portType>
	<wsdl:portType name="sfSOAP2">
		<wsdl:operation name="RegFactuSistemaFacturacion">
			<wsdl:input message="sfWdsl:EntradaRegFactuSistemaFacturacion"/>
			<wsdl:output message="sfWdsl:RespuestaRegFactuSistemaFacturacion"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="sfVerifactu" type="sfWdsl:sfSOAP1">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="RegFactuSistemaFacturacion">
			<soap:operation soapAction=""/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		
	</wsdl:binding>
	<wsdl:binding name="sfRequerimiento" type="sfWdsl:sfSOAP2">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="RegFactuSistemaFacturacion">
			<soap:operation soapAction=""/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="sfVerifactu">
		<!-- Entorno de PRODUCCION -->
		<wsdl:port name="SistemaVerifactu" binding="sfWdsl:sfVerifactu">
			<soap:address location="xxxxxxxxxx"/>
		</wsdl:port>
		<!-- Entorno de PRODUCCION para acceso con certificado de sello -->
		<wsdl:port name="SistemaVerifactuSello" binding="sfWdsl:sfVerifactu">
			<soap:address location="xxxxxxxxxx"/>
		</wsdl:port>
		<!-- Entorno de PRUEBAS -->
		<wsdl:port name="SistemaVerifactuPruebas" binding="sfWdsl:sfVerifactu">
			<soap:address location="xxxxxxxxxx"/>
		</wsdl:port>
		<!-- Entorno de PRUEBAS para acceso con certificado de sello -->
		<wsdl:port name="SistemaVerifactuPruebasSello" binding="sfWdsl:sfVerifactu">
			<soap:address location="xxxxxxxxxx"/>
		</wsdl:port>
	</wsdl:service>
	<wsdl:service name="sfRequerimiento">
		<!-- Entorno de PRODUCCION -->
		<wsdl:port name="SistemaRequerimiento" binding="sfWdsl:sfRequerimiento">
			<soap:address location="xxxxxxxxxx"/>
		</wsdl:port>
		<!-- Entorno de PRODUCCION para acceso con certificado de sello -->
		<wsdl:port name="SistemaRequerimientoSello" binding="sfWdsl:sfRequerimiento">
			<soap:address location="xxxxxxxxxx"/>
		</wsdl:port>
		<!-- Entorno de PRUEBAS -->
		<wsdl:port name="SistemaRequerimientoPruebas" binding="sfWdsl:sfRequerimiento">
			<soap:address location="xxxxxxxxxx"/>
		</wsdl:port>
		<!-- Entorno de PRUEBAS para acceso con certificado de sello -->
		<wsdl:port name="SistemaRequerimientoPruebasSello" binding="sfWdsl:sfRequerimiento">
			<soap:address location="xxxxxxxxxx"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
